log:
  serverList:
    serverA:
      remoteServer: ***.**.***.*
      user: ****
      password: ************
      remotePath: /****/
    serverB:
      remoteServer: ***.**.***.***
      user: *********
      password: ************
      remotePath: /****/
