log:
  serverList:
    serverA:
      remoteServer: 101.42.252.8
      user: root
      password: YaNan19980224
      remotePath: /root/
    serverB:
      remoteServer: 101.43.214.125
      user: fanzheng
      password: buaa@fanzheng666
      remotePath: /fanzheng/home/
