log:
  serverList:
    serverA:
      ip: ***.**.***.*
      user: ****
      password: ****************
      path: /****/
    serverB:
      ip: ***.**.***.*
      user: ****
      password: ****************
      path: /****/
